### PR TITLE
Some fixes for ruby 2.4.1 compatibility

### PR DESCRIPTION
**Pull request by SamMolokanov**
Hi there! 

On ruby-2.4.1 it raises an error:

```
     NoMethodError:
       undefined method `<<' for {:read_timeout=>60, :continue_timeout=>nil, :debug_output=>nil}:Hash
       Did you mean?  <
     # .rvm/gems/ruby-2.4.1/gems/fakeweb-1.3.0/lib/fake_web/ext/net_http.rb:50:in `request_with_fakeweb'
```

I made some little fixes in order to use the gem with ruby-2.4.1. May be someone would find it helpful.

```
# Gemfile

group :test do
  gem "fakeweb", github: "SamMolokanov/fakeweb", branch: "ruby-2-4-1-support"
end
```

#57

### CODE REVIEW

**Comment by xanview** [comment]
Same problem here, thank you for the workaround :) - please merge!

**Comment by SamMolokanov** [comment]
Closing this since @chrisk continued working. If anything could be useful from this PR, please let me know. Cheers!

**Comment by chrisk** [comment]
Hey Sam, thanks for posting this! If it's okay, I'd like to leave it open for a little while longer until I've had time to review everything you did and make sure nothing falls through the cracks... sorry to pollute your PR list. I should have everything reviewed and merged soon.

**Comment by chrisk** [comment]
Hey @SamMolokanov, would you mind switching to this repo's master branch and seeing if everything works for your project? I have versions of all these fixes merged now (along with many others), but would like to get some users to test while I update the docs, etc. before releasing.

```
# Gemfile

gem "fakeweb", github: "chrisk/fakeweb", branch: "master"
```

**Comment by SamMolokanov** [comment]
Hi @chrisk thank you for the update! 
Your latest build works perfect 👍 

PS. I have added a post-install message for people who use temporary solution.

**Comment by SamMolokanov** [comment]
Hi @chrisk! can I close this PR? :)

**Comment by chrisk** [comment]
Hi Sam, thanks for testing! Good idea about the post-install message. Yes, we can close this now. Thanks for all your help.

**Pull request closed without merging**
